import { Printer } from 'lucide-react'
import { Button } from '../ui/Button'
import { formatDate } from '../../lib/utils'
import type { BabyProfile, DoctorVisit, GrowthEntry, RecordedMilestone } from '../../store/useAppStore'

interface VisitBriefProps {
  baby: BabyProfile
  visit: DoctorVisit
  weeks: number
  growth: GrowthEntry[]
  recordedMilestones: RecordedMilestone[]
}

/**
 * "Ace the checkup" — a one-page, printable summary of everything worth
 * bringing to a pediatrician visit: growth trend, recent milestones, and the
 * prepared question list. Rendered inside a Modal; `.print-brief` is hidden
 * from screen-print rules everywhere else in the app (see index.css) so
 * printing this produces a clean single page with no app chrome.
 */
export function VisitBrief({ baby, visit, weeks, growth, recordedMilestones }: VisitBriefProps) {
  const sortedGrowth = [...growth].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
  const latestGrowth = sortedGrowth[0]
  const priorGrowth = sortedGrowth[1]
  const recentMilestones = [...recordedMilestones]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 6)

  function delta(latest: number | null, prior: number | null): string {
    if (latest == null || prior == null) return ''
    const diff = latest - prior
    if (diff === 0) return '(no change)'
    return diff > 0 ? `(+${diff.toFixed(1)} since last)` : `(${diff.toFixed(1)} since last)`
  }

  return (
    <div>
      <div className="flex justify-end mb-3 print:hidden">
        <Button size="sm" onClick={() => window.print()}>
          <Printer size={14} /> Print / Save as PDF
        </Button>
      </div>

      <div className="print-brief bg-cream-50 rounded-2xl border-2 border-stone-100 p-5 space-y-5 text-stone-800">
        <div className="text-center border-b-2 border-stone-100 pb-3">
          <p className="font-display text-lg font-black">
            {baby.name ? `${baby.name}'s` : "Baby's"} Doctor Visit Brief
          </p>
          <p className="text-xs text-stone-400 mt-1">
            {visit.type} · {visit.date ? formatDate(visit.date) : 'Date TBD'} · Week {weeks} · Generated {formatDate(new Date().toISOString())}
          </p>
        </div>

        <div>
          <p className="text-xs font-black uppercase tracking-wide text-stone-400 mb-1.5">Growth</p>
          {latestGrowth ? (
            <div className="text-sm space-y-0.5">
              {latestGrowth.weightGrams != null && (
                <p>Weight: <strong>{(latestGrowth.weightGrams / 1000).toFixed(2)} kg</strong> {delta(latestGrowth.weightGrams, priorGrowth?.weightGrams ?? null)}</p>
              )}
              {latestGrowth.heightCm != null && (
                <p>Length/Height: <strong>{latestGrowth.heightCm} cm</strong> {delta(latestGrowth.heightCm, priorGrowth?.heightCm ?? null)}</p>
              )}
              {latestGrowth.headCircCm != null && (
                <p>Head circumference: <strong>{latestGrowth.headCircCm} cm</strong> {delta(latestGrowth.headCircCm, priorGrowth?.headCircCm ?? null)}</p>
              )}
              <p className="text-xs text-stone-400 mt-1">Last measured {formatDate(latestGrowth.date)}</p>
            </div>
          ) : (
            <p className="text-sm text-stone-400">No growth entries logged yet.</p>
          )}
        </div>

        <div>
          <p className="text-xs font-black uppercase tracking-wide text-stone-400 mb-1.5">Recent milestones</p>
          {recentMilestones.length > 0 ? (
            <ul className="text-sm space-y-1">
              {recentMilestones.map((m) => (
                <li key={m.id}>• {m.title} <span className="text-xs text-stone-400">({formatDate(m.date)})</span></li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-stone-400">No milestones recorded yet.</p>
          )}
        </div>

        <div>
          <p className="text-xs font-black uppercase tracking-wide text-stone-400 mb-1.5">Questions to ask</p>
          {visit.questions.length > 0 ? (
            <ul className="text-sm space-y-1.5">
              {visit.questions.map((q, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="w-3 h-3 rounded-sm border-2 border-stone-400 shrink-0 mt-0.5" />
                  {q}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-stone-400">No questions added yet.</p>
          )}
        </div>

        <p className="text-[10px] text-stone-400 text-center pt-2 border-t border-stone-100">
          Generated by Parents' Little Helper · Not medical advice · For discussion with your pediatrician only
        </p>
      </div>
    </div>
  )
}
